# Generated by Django 4.0.1 on 2022-01-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('title', models.CharField(blank=True, default='', max_length=80, verbose_name='Назва бота')),
                ('token', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Токен бота')),
                ('server_url', models.CharField(blank=True, default='', max_length=200, verbose_name='Webhook Url')),
                ('nova_poshta_api', models.CharField(blank=True, max_length=200, verbose_name='Nova Poshta API')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
