# Generated by Django 4.0.1 on 2022-02-01 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botconfig',
            options={'verbose_name': 'Налаштування', 'verbose_name_plural': 'Налаштування бота'},
        ),
    ]
