# Generated by Django 4.0.1 on 2022-01-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія товару', 'verbose_name_plural': 'Категорії товарів'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.IntegerField(default=1, help_text='Чим вище пріоритет, тим вище відображається категорія', verbose_name='Пріоритет категорії'),
        ),
    ]
