# Generated by Django 4.0.1 on 2022-01-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(default='', max_length=255, verbose_name='ФІО користувача'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telegram_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Username'),
        ),
    ]
