# Generated by Django 4.0.1 on 2022-01-27 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_shop_options_shop_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Назва товару')),
                ('excerpt', models.CharField(max_length=200, verbose_name='Короткий опис')),
                ('description', models.TextField(verbose_name='Повний опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product-img/', verbose_name='Зображення')),
                ('price', models.FloatField(default=0, verbose_name='Ціна')),
                ('quantity', models.IntegerField(default=0, verbose_name='Кількість товару')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='shop.category', verbose_name='Категорія')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product-img/', verbose_name='Зображення')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
