# Generated by Django 4.0.1 on 2022-02-01 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_cart_total_cart_total_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_message_id',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ФІО користувача'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, default=None, editable=False, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='', max_length=255, verbose_name='ФІО покупця')),
                ('phone_number', models.CharField(default='', max_length=64, verbose_name='Номер телефону')),
                ('city', models.CharField(default='', max_length=200, verbose_name='Місто')),
                ('address', models.CharField(default='', max_length=255, verbose_name='Адреса доставки')),
                ('post_number', models.CharField(default='', max_length=32, verbose_name='Номер відділення')),
                ('total', models.FloatField(default=0, verbose_name='Загальна сума замовлення')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('pending', 'Pending payment'), ('refunded', 'Refunded')], max_length=25, verbose_name='Статус замовлення')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='shop.customer')),
            ],
        ),
    ]
