# Generated by Django 4.0.1 on 2022-02-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Інфо', 'verbose_name_plural': 'Інформація про магазин'},
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Адреса доставки'),
        ),
        migrations.AddField(
            model_name='customer',
            name='post_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Номер відділення'),
        ),
    ]
