# Generated by Django 4.0.1 on 2022-02-02 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_order_options_alter_shop_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Номер відділення'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
    ]
