# Generated by Django 4.0.1 on 2022-02-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.FloatField(default=0, verbose_name='Загальна вартість'),
        ),
    ]
