# Generated by Django 4.0.1 on 2022-02-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_order_options_remove_cart_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='productimage',
            name='main_image',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('pending', 'Pending payment'), ('refunded', 'Refunded')], default='processing', max_length=25, verbose_name='Статус замовлення'),
        ),
    ]
